name : "Next Innovations Company Website Deployment"

on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy-to-staging-job:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write
            packages: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install dependencies and zip 
              run: |
                cd ./backend

                echo "Composer Installing..."
                composer install

                echo "Npm  Installing..."
                npm uninstall vite
                npm install vite@6 --save-dev
                npm install

                ls






