name : "Next Innovations Company Website Deployment"

on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-frontend:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write
            packages: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install dependencies and build 
              run: |
                ls
                cd ./frontend
                npm ci
                npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: frontend-build
                path: frontend/dist

            - name: Install JP frontend and build
              run: |
                cd ./frontend-jp 
                npm ci
                npm run build
              
            - name: Upload JP frontend build artifact
              uses: actions/upload-artifact@v4
              with: 
                name: jp-frontend-build
                path: frontend-jp/dist

    move-files-staging-job:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write
            packages: write
        
        needs:  build-frontend

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                name: frontend-build
                path: frontend/dist

            - name: Install dependencies and zip
              run: |
                # Backend build
                cd ./backend

                echo "Composer Installing..."
                composer install

                echo "Npm Installing..."
                npm uninstall vite
                npm install vite@6 --save-dev
                npm install
                npm run build

                echo "Zipping Backend..."
                cd ..
                tar -czf backend.tar.gz backend

                # Frontend build
                echo "Moving Frontend Dist to Root Dir"
                cd ./frontend
                echo "Checking frontend Dist Folder"
                mv dist ..
                cd ..
                ls
                tar -czf dist.tar.gz dist
                ls

            - name: Download jp build artifact
              uses: actions/download-artifact@v4
              with:
                name: jp-frontend-build
                path: frontend-jp/dist

            - name: Install dependencies and zip
              run : |
                   echo "Checking Jp frontend Dist Folder"
                   ls
                   cd ./frontend-jp
                   ls
                   tar -czf jpdist.tar.gz dist
                   ls
                   mv jpdist.tar.gz ..
                   ls

            - name: Copy NextInnovation Company Website Backend over scp
              uses: appleboy/scp-action@v0.1.7
              with:
                    source: backend.tar.gz
                    target: /home/ubuntu/nextinnovations-company-networks/
                    host: ${{ secrets.STAGING_HOST }}
                    username: ${{ secrets.STAGING_USER }}
                    key: ${{ secrets.STAGING_KEY }}
            
            - name: Copy NextInnovation Company Website Frontend over scp
              uses: appleboy/scp-action@v0.1.7
              with:
                     source: dist.tar.gz
                     target: /home/ubuntu/nextinnovations-company-networks/
                     host: ${{ secrets.STAGING_HOST }}
                     username: ${{ secrets.STAGING_USER }}
                     key: ${{ secrets.STAGING_KEY }}

            - name: Copy Japan NextInnovation Company Website Frontend over scp
              uses: appleboy/scp-action@v0.1.7
              with:
                      source: jpdist.tar.gz
                      target: /home/ubuntu/nextinnovations-company-networks/
                      host: ${{ secrets.STAGING_HOST }}
                      username: ${{ secrets.STAGING_USER }}
                      key: ${{ secrets.STAGING_KEY }}

    SSH-and-deploy:
        runs-on: ubuntu-latest
                
        permissions:
                contents: read
                id-token: write
                packages: write
                        
        needs:  [build-frontend , move-files-staging-job]
        steps:
            - name: Executing remote ssh commands
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.STAGING_HOST }}
                username: ${{ secrets.STAGING_USER }}
                key: ${{ secrets.STAGING_KEY }}
                script: |
                    sudo rm -rf /home/ubuntu/nextinnovations-company-networks/backend
                    sudo rm -rf /home/ubuntu/nextinnovations-company-networks/dist
                    sudo rm -rf /home/ubuntu/nextinnovations-company-networks/jpfrontend


                    mkdir /home/ubuntu/nextinnovations-company-networks/jpfrontend
                    
                    

                    sudo tar -xf /home/ubuntu/nextinnovations-company-networks/backend.tar.gz -C /home/ubuntu/nextinnovations-company-networks
                    sudo tar -xf /home/ubuntu/nextinnovations-company-networks/dist.tar.gz -C /home/ubuntu/nextinnovations-company-networks
                    sudo tar -xf /home/ubuntu/nextinnovations-company-networks/jpdist.tar.gz -C /home/ubuntu/nextinnovations-company-networks/jpfrontend


                    sudo rm -rf /home/ubuntu/nextinnovations-company-networks/backend.tar.gz
                    sudo rm -rf /home/ubuntu/nextinnovations-company-networks/dist.tar.gz
                    sudo rm -rf /home/ubuntu/nextinnovations-company-networks/jpdist.tar.gz


                    sudo rm -rf /var/www/dist
                    sudo rm -rf /var/www/jpdist

                    sudo cp -r /home/ubuntu/nextinnovations-company-networks/dist /var/www/dist
                    sudo cp -r /home/ubuntu/nextinnovations-company-networks/jpfrontend/dist /var/www/jpdist




                    # Run backend migrations
                    cd /home/ubuntu/nextinnovations-company-networks/backend
                    php artisan migrate --force


                    sudo rm -rf /var/www/backend
                    sudo cp -r /home/ubuntu/nextinnovations-company-networks/backend /var/www/backend

                    sudo chown -R www-data:www-data /var/www/backend

                    sudo systemctl restart nginx.service





