name : "Next Innovations Company Website Deployment"

on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-frontend:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write
            packages: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Install dependencies and build 
              run: |
                ls
                cd ./frontend
                npm ci
                npm run build

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: frontend-build
                path: frontend/dist

    deploy-to-staging-job:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write
            packages: write
        
        needs:  build-frontend

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                name: frontend-build
                path: frontend/dist

            - name: Install dependencies and zip 
              run: |
                cd ./backend

                echo "Composer Installing..."
                composer install

                echo "Npm  Installing..."
                npm uninstall vite
                npm install vite@6 --save-dev
                npm install
                npm run build

                echo "Zipping Assets..."
                cd ../
                tar -czf backend.tar.gz backend


                echo "Moving Frontend Dist to Root Dir"
                mv frontend/dist NextInnovation_company_website
                ls
                tar -czf dist.tar.gz dist
                ls


            - name: Copy NextInnovation Company Website Backend over scp
              uses: appleboy/scp-action@v0.1.7
              with:
                    source: backend.tar.gz
                    target: /home/ubuntu/nextinnovations-company-networks/
                    host: ${{ secrets.STAGING_HOST }}
                    username: ${{ secrets.STAGING_USER }}
                    key: ${{ secrets.STAGING_KEY }}
            
            - name: Copy NextInnovation Company Website Frontend over scp
              uses: appleboy/scp-action@v0.1.7
              with:
                     source: dist.tar.gz
                     target: /home/ubuntu/nextinnovations-company-networks/
                     host: ${{ secrets.STAGING_HOST }}
                     username: ${{ secrets.STAGING_USER }}
                     key: ${{ secrets.STAGING_KEY }}


                    # /var/www/html/NextInnovation_company_website/backend/public
                    # /var/run/php/php8.2-fpm.sock







